add a check to make sure we don't delete /var/www

diff --git a/openapp-drupal-deletesite b/openapp-drupal-deletesite
--- a/openapp-drupal-deletesite
+++ b/openapp-drupal-deletesite
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 fatal() {
-    echo $1
+    echo $1 >&2
     exit 1
 }
 
@@ -32,6 +32,7 @@ SITE_DIR=$(get_pref "Site path")
 TMPDIR=$(mktemp -d $(pwd)/XXXXXXXXX)
 DATE=$(date +%Y%m%d)
 
+[ -z ${DBNAME} -o -z ${MYSQL_USER} -o -z ${SITE_DIR} ] && fatal "Could not find one of the needed variables to clean up"
 /usr/bin/mysqldump ${OPTS} ${DBNAME} | gzip > ${TMPDIR}/mysqldump.gz
 rsync -a ${DRUPAL_DIR}/${SITE_DIR} ${TMPDIR}
 
